# Generated by Django 2.2.14 on 2020-07-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=256)),
                ('time', models.TimeField()),
                ('horses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventsapp_horses', to='home.Location')),
            ],
        ),
    ]
