# Generated by Django 2.2.14 on 2020-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room1', models.CharField(max_length=256)),
                ('room2', models.CharField(max_length=256)),
                ('room3', models.CharField(max_length=256)),
            ],
        ),
    ]
